FROM python:3.13

WORKDIR /price_tracker

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN python -m playwright install --with-deps chromium

COPY . .

RUN chmod +x entry.sh

ENTRYPOINT ["./entry.sh"]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]